luku1_str = input("Anna minulle kolme kokonaislukua.\n")
luku2_str = input()
luku3_str = input()
luku1 = float(luku1_str)
luku2 = float(luku2_str)
luku3 = float(luku3_str)
summa = float(luku1 + luku2 + luku3)
tulo = float(luku1 * luku2 * luku3)
keskiarvo = float(summa / 3)
print("Lukujen summa on: " + str(summa) + " , tulo on: " + str(tulo) + " ja keskiarvo: " + str(keskiarvo) + ".")
